# CLASE 07 Creación de Arrays
## Prof. Andrés Mena Abarca
### Estudiante: Mariana Villalobos Vargas 

### Crear un array a partir de una lista

In [1]:
import numpy as np



### Crear un array de ceros de tamaño 5x5

In [3]:
array_ceros= np.zeros ((5,5))
print (array_ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Crear un array de unos de tamaño 3x3

In [ ]:
array_unos = np.ones((2,3)) #Primer valor es "x" o filas y el segundo es "y" o columnas.
print (array_unos)

[[1. 1. 1.]
 [1. 1. 1.]]


### Crear un array con valores espaciados uniformemente de 0 a 9

In [14]:
#Código rear un array con valores espaciados uniformemente de 0 a 9
array_lineal= np.linspace(0,9,10) #Datos del 0 (inicio) al 9 (límite) y cuántos valores quiero espaciar (10).
print(array_lineal)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### #Crear un array con 6 valores espaciados linealmente entre 0 y 1


In [ ]:
#Código crear un array con 6 valores espaciados linealmente entre 0 y 1
array_reto= np.linspace(0,1,6) #Datos del 0 (inicio) al 1 (límite) y cuántos valores quiero espaciar (6).
print(array_reto)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

### Realizar una suma, resta, multiplicación y división entre dos arrays

In [ ]:
array_salario = np.array([50,40,20]) 
array_propinas = np.array([6,4,9])

#Código realizar una suma, resta, multiplicación y división entre dos arrays

suma = array_salario + array_propinas
resta = array_salario - array_propinas
division = array_salario / array_propinas
multiplicacion = array_salario * array_propinas

# Salida

print("La suma es: ",suma) #Tienen que tener las mismas dimensiones.
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)

La suma es:  [56 44 29]
La resta es:  [44 36 11]
La multiplicacion es:  [300 160 180]
La division es:  [ 8.33333333 10.          2.22222222]


In [ ]:
#Calcular el producto punto de dos arrays


In [ ]:
#Transponer un array


# Operaciones Estadísticas

In [ ]:
#Calcular la media, suma, valor mínimo y valor máximo de un array


# Crear un array NumPy
array_numeros = np.array([5, 2, 4, 1, 3])

# Calcular la media
media= np.mean(array_numeros)
print (f'La media aritmética es: {media}')
# Calcular la suma
suma_calc = np.sum(array_numeros)
print(f'La suma de los números es {suma_calc}')

# Calcular el valor mínimo
valor_min= np.min(array_numeros)
print(f'El valor mínimo de los números es {valor_min}')

# Calcular el valor máximo
valor_max= np.max(array_numeros)
print(f'El valor mínimo de los números es {valor_max}')


La media aritmética es: 3.0
La suma de los números es 15
El valor mínimo de los números es 1
El valor mínimo de los números es 5
El valor mínimo de los números es 5


'\n# Mostrar los resultados\nprint("La media es:", media)\nprint("La suma es:", suma)\nprint("El valor mínimo es:", valor_minimo)\nprint("El valor máximo es:", valor_maximo)\n'

In [ ]:
#Cambiar la forma de un array "reshape"


# Crear un array original
array_original = np.array([1, 2, 3, 4, 5, 6])
print(array_original)

# Nueva forma deseada (2 filas y 3 columnas)
array_reshapeado = array_original.reshape(2,3) #Tiene que calzar la cantidad de datos con la disposición.
print (array_reshapeado)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


'\n# Imprimir el array original y el reshapeado\nprint("Array original:", array_original)\nprint("Array reshapeado:", array_reshapeado)\n'

# Álgebra Lineal

### Calcular el determinante de una matriz 2x2

In [ ]:
nuevo_array = np.array([[1,2],[2,5]])

#Código para calcular el determinante de una matriz 2x2

#print(determinante)

### Calcular la matriz inversa de una matriz 3x3

In [ ]:
# Definir la matriz 3x3


# Calcular la matriz inversa


# Imprimir la matriz inversa



### Calcular los valores propios y vectores propios de una matriz 4x4

In [ ]:

# Definir la matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Calcular valores propios y vectores propios


# Separar valores propios y vectores propios
 # Parte real de los valores propios complejos
  # Parte real de los vectores propios complejos

# Imprimir resultados
'''
print("Valores propios:", autovalores)
print("Vectores propios:")
for i in range(len(autovectores)):
    print(f"Vector propio {i+1}:", autovectores[i])
'''

# Funciones Universales

In [ ]:
# Crear un array con ángulos
array_angulos = np.array([0, np.pi/2, np.pi])

# Calcular el seno de los ángulos


# Calcular el coseno de los ángulos


# Calcular la exponencial de los ángulos


# Calcular el logaritmo natural de los ángulos




In [ ]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Obtener la primera fila del array


# Obtener la última columna del array
  # [3, 6, 9]

# Obtener una submatriz que contiene la segunda fila y las dos primeras columnas
  # [4, 5]

# Imprimir los subconjuntos de datos extraídos


# Generación de Números Aleatorios

In [ ]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100


In [ ]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1


In [ ]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)



## Ejercicios reales prácticos


In [39]:
mariana = np.array([7,9,2]) # Acción, Comedia, Drama
avatar = np.array ([10,1,5]) #Más acción, menos comedia.
brave_heart = np.array ([8, 1, 7]) #Más acción, menos comedia

#Calcular la similitud de cada película con los gustos de Mariana.

similitud_p1= np.dot(mariana,avatar) #Producto por punto
similitud_p2= np.dot(mariana,brave_heart) 

print(f'La similitud con Avatar es de {similitud_p1}')
print (f'La similitud con Brave Heart es {similitud_p2}')

if similitud_p1 > similitud_p2:
    print ("Recomendamos ver Avatar.")
else:
    print ("Recomendamos Brave Heart")

La similitud con Avatar es de 89
La similitud con Brave Heart es 79
Recomendamos ver Avatar.


## Caso Estudio Relación

In [47]:
import numpy as np
#Datos Tipo cambio dólar (últimos 10 meses) / Índice precio al consumidor, métrica mensual (últimos 10 meses)
tipo_cambio = np.array([506.96, 505.00, 504.27, 505.52, 506.23, 506.23, 506.23, 506.58, 506.87, 507.25])
ipc= np.array([109.46, 109.55, 109.71, 109.57, 109.70,109.33, 108.85,109.36, 110.39, 110.79])

# Calcular coeficiente de correlación

correlacion= np.corrcoef(tipo_cambio, ipc)[0,1]

print (f'El coeficiente de correlación entre el tipo de cambio y el ipc es de {correlacion:.2f}')


El coeficiente de correlación entre el tipo de cambio y el ipc es de 0.32


## Caso #3. Estudio de Horas vs Notas

In [71]:
import numpy as np
# Datos: Horas de estudio dedicadas y Notas de examen obtenidas.
horas_est= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
notas_obt= np.array([50, 55, 60, 63, 67, 72, 75, 78, 81, 85])

#Cálculos crecimiento del promedio del puntaje por hora de estudio.

dif_notas= np.diff(notas_obt) #Diferencias entre notas consecutivas.
print (dif_notas)

promedio_incremento= np.mean(dif_notas)
print (f'El incremento por cada hora de estudio es {promedio_incremento:.2f}')

# Estimación de puntaje si estudio 12 horas:
horas_estudio=12
nota_calcu= (horas_estudio - horas_est[-1]) * promedio_incremento + notas_obt[-1]
print (f'La nota máxima por obtener con {horas_estudio} horas de estudio sería {nota_calcu:.0f}')

[5 5 3 4 5 3 3 3 4]
El incremento por cada hora de estudio es 3.89
La nota máxima por obtener con 12 horas de estudio sería 93
